    <!--[if lt IE 9]>
    <script src="<?php echo $this->basepath(); ?>/lib/es5-shim/es5-shim.js"></script>
    <script src="<?php echo $this->basepath(); ?>/lib/json3/lib/json3.min.js"></script>
    <![endif]-->

    <script src="<?php echo $this->basepath(); ?>/asset/js/globals.js"></script>
    <script src="<?php echo $this->basepath(); ?>/lib/angular/angular.min.js"></script>
    <script src="<?php echo $this->basepath(); ?>/lib/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

    <?php echo $this->headScript(); ?>
</body>
</html>
