<?php
/* @var Zend\View\Renderer\PhpRenderer $this */
echo $this->doctype();
?>

<!--[if lt IE 7]>
<html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en" class="no-js"> <!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SpaceAPI Hosting</title>
    <meta name="description" content="Create a new endpoint in the SpaceAPI cloud.">
    <meta name="viewport" content="width=device-width">

    <link rel="author" href="<?php echo $this->basePath(); ?>/humans.txt" />

    <link href="<?php echo $this->basePath('img/favicon.ico'); ?>" type="image/x-icon" rel="shortcut icon">
    <link href="<?php echo $this->basePath('img/favicon.gif'); ?>" type="image/x-icon" rel="shortcut icon">

    <?php
    // add stylesheets to this array, this is a LIFO, the last element
    // gets first rendered, all the stylesheets from the views are
    // loaded after them
    $styles = array(
        $pageStyleSheet,
        "lib/bootstrap/dist/css/bootstrap.min.css",
    );

    foreach ($styles as $style) {
        $this->headLink()->prependStylesheet($this->basePath() . "/$style");
    }
    ?>

    <?php echo $this->headLink() ?>

</head>
<body>
    <!--[if lt IE 7]>
    <section class="browsehappy">
        You are using an <strong>outdated</strong> browser.
        Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
    </section>
    <![endif]-->