<?php
    /* @var Zend\View\Renderer\PhpRenderer $this */
    echo $this->render('layout/_header.phtml', array(
        'pageStyleSheet' => 'styles/page-default.min.css'
    ));
?>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">

        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src="/img/spaceapi-logo-white.png"></a>
        </div>

        <ul class="nav navbar-nav vertical small visible-340">
            <li class="mainmenu-getting-started"><a href="/docs/getting-started"><span class="glyphicon glyphicon-play"></span> Getting started</a></li>
            <li class="mainmenu-documentation"><a href="http://spaceapi.net/documentation"><span class="glyphicon glyphicon-info-sign"></span> Documentation</a></li>
            <li class="mainmenu-contribute"><a href="/contribute"><span class="glyphicon glyphicon-road"></span> Contribute</a></li>
            <li class="mainmenu-edit"><a href="/endpoint/edit"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
            <li class="mainmenu-create"><a href="/endpoint/create"><span class="glyphicon glyphicon-plus"></span> Create</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-left hidden-340">

            <li class="hidden-340 mainmenu-getting-started"><a href="/docs/getting-started"><span class="glyphicon glyphicon-play visible-445"></span> <span class="hidden-445">Getting started</span></a></li>
            <li class="hidden-500 mainmenu-documentation"><a href="http://spaceapi.net/documentation"><span class="glyphicon glyphicon-info-sign visible-620"></span> <span class="hidden-620">Documentation</span></a></li>
            <li class="hidden-500 mainmenu-contribute"><a href="/contribute"><span class="glyphicon glyphicon-road visible-700"></span> <span class="hidden-700">Contribute</span></a></li>
            <li>
                <ul class="nav navbar-nav vertical small visible-500">
                    <li class="mainmenu-getting-started visible-340"><a href="/docs/getting-started"><span class="glyphicon glyphicon-play visible-445"></span></a></li>
                    <li class="mainmenu-documentation"><a href="http://spaceapi.net/documentation"><span class="glyphicon glyphicon-info-sign"></span></a></li>
                    <li class="mainmenu-contribute"><a href="/contribute"><span class="glyphicon glyphicon-road"></span></a></li>
                </ul>
            </li>
            <li>
                <ul class="nav navbar-nav endpoint-actions vertical small visible-840">
                    <li class="mainmenu-edit"><a href="/endpoint/edit"><span class="glyphicon glyphicon-pencil"></span></a></li>
                    <li class="mainmenu-create"><a href="/endpoint/create"><span class="glyphicon glyphicon-plus"></span></a></li>
                </ul>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right endpoint-actions big hidden-840">
            <li class="mainmenu-edit"><a href="/endpoint/edit"><span class="glyphicon glyphicon-pencil"></span> <span class="hidden-840">Edit</span></a></li>
            <li class="mainmenu-create"><a href="/endpoint/create"><span class="glyphicon glyphicon-plus"></span> <span class="hidden-840">Create</span></a></li>
        </ul>

    </nav>

    <div class="flex-parent-default">
        <div class="content">
            <?php echo $this->content; ?>
        </div>
        <div class="sidebar hidden-840 container">

            <section class="participants">
                <h1>Participating Hackerspaces</h1>

                <ul class="clearfix">
                    <li>/dev/tal</li>
                    <li>57North Hacklab</li>
                    <li>[hsmr]</li>
                    <li>Ace Monster Toys</li>
                    <li>ACKspace</li>
                    <li>AFRA</li>
                    <li>Apollo-NG</li>
                    <li>backspace</li>
                    <li>base48</li>
                    <li>Bastli</li>
                    <li>BinarySpace</li>
                    <li>Bitlair</li>
                    <li>brmlab</li>
                    <li>Bytespeicher</li>
                    <li>bytewerk</li>
                    <li>C3D2 GCHQ</li>
                    <li>CCCFr</li>
                    <li>Chaos Darmstadt</li>
                    <li>Chaos inKL.</li>
                    <li>Chaosdorf</li>
                    <li>Chaostreff Chemnitz</li>
                    <li>Chaostreff-Dortmund</li>
                    <li>CommonGround</li>
                    <li>coredump</li>
                    <li>DevLoL</li>
                    <li>Edinburgh Hacklab</li>
                    <li>Embassy of Nerdistan</li>
                    <li>Entropia</li>
                    <li>FamiLAB</li>
                    <li>FAU FabLab</li>
                    <li>FIXME</li>
                    <li>Foomatic</li>
                    <li>Frack</li>
                    <li>GarageLab e.V.</li>
                    <li>Garoa Hacker Clube</li>
                    <li>H.A.C.K.</li>
                    <li>HacDC</li>
                    <li>Hack42</li>
                    <li>Hackburg</li>
                    <li>Hackeriet</li>
                    <li>Hackerspace Bremen e.V.</li>
                    <li>Hackerspace KRK</li>
                    <li>Hackerspace.gr</li>
                    <li>Hackerspace.sg</li>
                    <li>Hacksaar</li>
                    <li>Hackspace Siegen</li>
                    <li>HeatSync Labs</li>
                    <li>Hickerspace</li>
                    <li>Hive13</li>
                    <li>HSMTY</li>
                    <li>HTU Graz - Basisgruppe Informatik</li>
                    <li>HTU Graz - Basisgruppe Telematik</li>
                    <li>Istanbul Hackerspace</li>
                    <li>IT-Syndikat</li>
                    <li>Jeanne D'Hack</li>
                    <li>Krautspace</li>
                    <li>Laboratorio Hacker de Campinas</li>
                    <li>Lamba Labs</li>
                    <li>Le Loop</li>
                    <li>Mainframe</li>
                    <li>MakeHackVoid Canberra</li>
                    <li>Makers Local 256</li>
                    <li>Maschinenraum</li>
                    <li>MechArtLab</li>
                    <li>MetaMeute</li>
                    <li>MidsouthMakers</li>
                    <li>miLKlabs</li>
                    <li>Milwaukee Makerspace</li>
                    <li>MuCCC</li>
                    <li>nbsp</li>
                    <li>Netz39</li>
                    <li>Netzladen</li>
                    <li>Nicelab</li>
                    <li>Noisebridge</li>
                    <li>Noklab</li>
                    <li>Nottinghack</li>
                    <li>Nova Labs</li>
                    <li>NURDSpace</li>
                    <li>OpenLab</li>
                    <li>P-Space</li>
                    <li>Post Tenebras Lab</li>
                    <li>Progressbar</li>
                    <li>Randomdata</li>
                    <li>RaumZeitLabor</li>
                    <li>Reaktor 23</li>
                    <li>realraum</li>
                    <li>Recompile</li>
                    <li>RevSpace</li>
                    <li>Sabugosa</li>
                    <li>shackspace - stuttgart hackerspace</li>
                    <li>Sk1llz</li>
                    <li>Stratum 0</li>
                    <li>sublab</li>
                    <li>Sudo Room</li>
                    <li>syn2cat</li>
                    <li>SYNHAK</li>
                    <li>Taipei Hackerspace</li>
                    <li>Tampere Hacklab 5w</li>
                    <li>Tangleball</li>
                    <li>Technologia Incognita</li>
                    <li>TechTonik Labs</li>
                    <li>TOG</li>
                    <li>turmlabor</li>
                    <li>UrLab</li>
                    <li>VoidWarranties</li>
                    <li>Warsaw Hackerspace</li>
                    <li>Wolfplex Hackerspace</li>
                    <li>Xerocraft</li>
                </ul>
            </section>

            <hr style="border: 1px solid #aaa;">

            <section class="news">
                <h1>News</h1>
                <ul>
                    <li><span class="date">31.03</span> Attending <a href="http://eh14.easterhegg.eu/" target="_blank">EH14</a> on April 18th</li>
                </ul>
            </section>

        </div>
    </div>

<?php echo $this->render('layout/_footer.phtml'); ?>
