<?php
    /* @var Zend\View\Renderer\PhpRenderer $this */
    echo $this->doctype();
?>

<!--[if lt IE 7]>
<html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en" class="no-js" ng-app="saHosting"> <!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SpaceAPI Hosting</title>
    <meta name="description" content="Create a new endpoint in the SpaceAPI cloud.">
    <meta name="viewport" content="width=device-width">

    <link rel="author" href="humans.txt" />

    <link href="<?php echo $this->basePath('img/favicon.ico'); ?>" type="image/x-icon" rel="shortcut icon">
    <link href="<?php echo $this->basePath('img/favicon.gif'); ?>" type="image/x-icon" rel="shortcut icon">

    <?php
        // add stylesheets to this array, this is a LIFO, the last element
        // gets first rendered, all the stylesheets from the views are
        // loaded after them
        $styles = array(
            "styles/main.css",
            "lib/bootstrap/dist/css/bootstrap.css",
        );

        foreach ($styles as $style) {
            $this->headLink()->prependStylesheet($this->basePath() . "/$style");
        }
    ?>

    <?php echo $this->headLink() ?>

</head>
<body>

    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right" >
                <li><a href="<?php echo $this->basePath(''); ?>">Home</a></li>
                <li><a href="<?php echo $this->basePath('endpoint/create'); ?>">Create and endpoint</a></li>
            </ul>
            <h1>
                <img class="logo" alt="SpaceAPI" src="<?php echo $this->basePath('img/spaceapi-logo.png'); ?>">
            </h1>
        </div>
    </div>

    <!--[if lt IE 7]>
    <section class="browsehappy">
        You are using an <strong>outdated</strong> browser.
        Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
    </section>
    <![endif]-->

    <?php echo $this->content; ?>
    <footer></footer>

    <!--[if lt IE 9]>
    <script src="lib/es5-shim/es5-shim.js"></script>
    <script src="lib/json3/lib/json3.min.js"></script>
    <![endif]-->

    <script src="lib/angular/angular.min.js"></script>
    <script src="lib/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

    <?php echo $this->headScript(); ?>
</body>
</html>
